services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "8888:80"
    depends_on:
      - kibana
      - app_php
    container_name: app_nginx
  app_php:
    build: 
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: app_php
    restart: always
  elasticsearch:
    image: elasticsearch:8.12.2
    ports:
      - "9200:9200"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTIC_PASSWORD=29PLOV7enyBOdmOiHJ9o
      # - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - elastic-db:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=oktribyFAuY67nKIiUHJ
  bot:
    build:
      context: ./max
      dockerfile: Dockerfile
    container_name: max_bot
    ports:
      - "3000:3000"
    volumes:
      - ./max:/app 
      - .env:/app/.env
      - /app/node_modules
volumes:
  elastic-db: